config/routes.rb
Rails.application.routes.draw do
  # Root path
  root "posts#index"  # หน้าแรกของเว็บไซต์

  # Define routes for static pages
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  # Routes for resources
  resources :comments
  resources :likes, only: [:create, :destroy]
  resources :posts

  # Routes for Devise user authentication
  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  # Custom route for "My Posts" page
  get "my_posts", to: "posts#myposts", as: 'my_posts'

  # Search route for posts
  get "posts/search", to: "posts#search", as: :search_posts

  # Health check route
  get "up", to: "rails/health#show", as: :rails_health_check

  # Route to remove duplicate posts
  delete "posts/remove_duplicates", to: "posts#remove_duplicates", as: :remove_duplicates
end

app/views/layouts/_footer.html.erb
<footer class="bg-light text-dark text-center text-lg-start">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">Footer Content</h5>

        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
          molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
          voluptatem veniam, est atque cumque eum delectus sint!
        </p>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <a href="#!" class="text-dark">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-dark">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-dark">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-dark">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase mb-0">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-dark">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-dark">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-dark">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-dark">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.1);">
    © 2020 Copyright:
    <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Upload Post", new_post_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item">
          <%= link_to "About Page", home_about_path, class: "nav-link" %>
        </li>

       
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>



          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "My Posts", posts_myposts_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit account", edit_user_registration_path, class: "nav-link" ,style:"border:none"%>
        </li>
        
      </ul>

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Final Web" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="csrf-token" content="<%= csrf_meta_tags %>"
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %> 
    <%= turbo_include_tags %> 
  </head>

  <body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <!-- Logo -->
        <%= link_to "YourApp", root_path, class: "navbar-brand" %>

        <!-- Toggle for mobile view -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navigation Links -->
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto">
            <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Upload Post", new_post_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "About Page", about_path, class: "nav-link" %></li>
          </ul>

          <!-- Search Bar -->
          <%= form_with url: posts_path, method: :get, local: true, class: "d-flex" do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control me-2" %>
            <%= submit_tag "Search", class: "btn btn-primary" %>
          <% end %>

          <!-- Right Links (Sign In, Sign Up, Log Out) -->
          <ul class="navbar-nav ms-3">
            <% if user_signed_in? %>
              <!-- For logged-in users -->
              <li class="nav-item"><%= link_to "My Posts", my_posts_path, class: "nav-link" %></li>
              <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <!-- For users not logged in -->
              <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Main Content -->
    <%= yield %>

    <!-- Footer -->
    <%= render "layouts/footer" %>
  </body>
</html>